#!/usr/bin/perl

=head1 DOCUMENTATION

=head2 SYNOPSIS 

	NAME:     SetProject 
	Author:   Juan M. Lorenzo 
	Date:     Jan 1 2017
	          from SetProject December 15, 2011 
	Purpose:  Create Project Directories  
 		      Establishes system-wide and local directories
        Details:  "sub-packages" use
                  Project_Variables package 

        Usage:    directories can be turned
                  on/off with comment marks ("#")
                  
=head2 NEEDS

		Project

=cut

use Moose;

 use Project;
 my $Project = new Project();

 $Project->basic_dirs();
 $Project->system_dirs();
 $Project->make_local_dirs();
