#! /usr/bin/perl

# SCRIPT NAME
# iSave_bot_mute_picks.pl
# Purpose: Save final Bot Mute  
# Juan M. Lorenzo
# Sept. 15, 2011


# Use shell transparently to locate home directory before compilation

        my $library_location;

        BEGIN {
                use Shell qw(echo);

                $home_directory = ` echo \$HOME`;
                chomp $home_directory;
                $library_location = $home_directory.'/lsu/libAll';
        }

# LOAD GENERAL PERL LIBRARY
  use lib $library_location;

# LOAD SEISMIC UNIX GLOBAL SYSTEM LIBARAY
  use lib '/usr/local/pl/libAll';
  use SeismicUnix qw ($itemp_bot_mute_picks_sorted_par_ $ibot_mute_par_ );

# library path
  use lib './libAll';

# use library
# import system variables
  use System_Variables2;
  my ($DATA_SEISMIC_SU)      = System_Variables2::DATA_SEISMIC_SU();

# use library
# import system variables
  use iBot_Mute qw ($file_name);

# sufile names
  $sufile_in[1] 	=  $file_name;

# COPY DATA
# copy data
        $data_in[1]	= $itemp_bot_mute_picks_sorted_par_;
        $data_out[1]	= $ibot_mute_par_;
        $inbound[1]	= $DATA_SEISMIC_SU.'/'.$data_in[1].$sufile_in[1];
        $outbound[1]	= $DATA_SEISMIC_SU.'/'.$data_out[1].$sufile_in[1];

	@cp[1] =  (" cp							\\
		$inbound[1]						\\
		$outbound[1]						\\
		");


#  DEFINE FLOW(S)
	@flow[1] = (" 							\\
		@cp[1] 	 						\\
		&							\\
		"); 


# RUN FLOW(S)
       system @flow[1]; 
       system 'echo', @flow[1];	

