#! /usr/bin/perl

# SCRIPT NAME
# iSelect_tr_Sumute_bot.pl
# Purpose: Linear Bot Mute of Data 
# V1.
# April 2 2009 
# V1.2
# Aug 9, 2011


# Use shell transparently to locate home directory before compilation

        my $library_location;

        BEGIN {
                use Shell qw(echo);

                $home_directory = ` echo \$HOME`;
                chomp $home_directory;
                $library_location = $home_directory.'/lsu/libAll';
        }

# LOAD GENERAL PERL LIBRARY
  use lib $library_location;

# LOAD SEISMIC UNIX GLOBAL SYSTEM LIBARAY
  use lib '/usr/local/pl/libAll';
  use SeismicUnix;
  use SeismicUnix qw ($true $false $on $off $itemp_bot_mute_picks $itemp_bot_mute_picks_sorted_par $ibot_mute_par $ibot_mute_check_pickfile $suffix_su);

# library path
  use lib './libAll';

# use library
  use System_Variables2;
  my ($DATA_SEISMIC_SU) 	= System_Variables2::DATA_SEISMIC_SU();

# use library
  use iBot_Mute qw ($file_name $binheader_type $taup_data $panel_first $panel_last $panel_inc $traces_per_panel);

# sufile names
$N=1;
  $sufile_in[$N] 		= $file_name;
  $sufile_out[$N] 		= $sufile_in[1].$ibot_mute_par;
  $inbound[$N]	  		= $DATA_SEISMIC_SU.'/'.$sufile_in[1].$suffix_su;
  $outbound[$N]  		= $DATA_SEISMIC_SU.'/'.$sufile_out[1].$suffix_su;
$N=0;

# SUFILTER parameters 
  my($ref_sufilter_bandpass,$sufilter_Nmax) 					= iBot_Mute::sufilter();

# SUGAIN parameters
  my($ref_sugain_wagc,$ref_sugain_agc,$ref_sugain_pbal,$ref_sugain_note,$sugain_Nmax)   		= iBot_Mute::sugain();

#SUWIND  PARAMETERS
  my($ref_suwind_key,$ref_suwind_min,$ref_suwind_max,$suwind_Nmax) 		= iBot_Mute::suwind();

# SUGAIN 
$sugain_N=$sugain_Nmax;
print("sugain_Nmax=$sugain_Nmax\n\n");
for($N=1;$N<=$sugain_N;$N++) {;
	$sugain[$N]  =  (" sugain 	  			\\
		wagc=$$ref_sugain_wagc[$N]		  	\\
		pbal=$$ref_sugain_pbal[$N]	  		\\
		agc=$$ref_sugain_agc[$N]	  		\\
     ");
}
$N=0;


# FILTER 
$sufilter_N = $sufilter_Nmax;
for($N=1;$N<=$sufilter_N;$N++){
	$sufilter[$N] =  (" sufilter 		  		\\
		f=$$ref_sufilter_bandpass[$N]			\\
     ");
}
$N=0;

# SUWIND 
$suwind_N = $suwind_Nmax;
for($N=1;$N<=$suwind_N;$N++){
	$suwind[$N]  =  (" suwind 	            		\\
		key=$$ref_suwind_key[$N]			\\
		min=$$ref_suwind_min[$N]			\\
		max=$$ref_suwind_max[$N]			\\
              ");
}
$N=0;

# DISPLAY DATA
# display data
	for ($panel=$panel_first; $panel<=$panel_last; $panel = $panel + $panel_inc){	
$N=1;
$P=$panel;		
 		if($taup_data == $true) {
		($sutaup_np,$pmin,$sutaup_pmax,$sutaup_dx,$dp) = iBot_Mute::tp_dict();
		   $suximage_x0[$N]= $pmin;
		   $suximage_dx[$N]= 1000 * $dp;
		}
		elsif ($taup_data == $false) {
		   #$suximage_x0[$N]= 1;
		   #$suximage_dx[$N]= ;
		}
		$suximage_binhdr[$N] 		= $binheader_type;
		$suximage_xlabel[$N]    	= 'tracr';
		$suximage_windowtitle[$N]	= '\('.$N.'\)\ '.'PICK\ BOTTOM\ MUTE\ \ '.$file_name.'\ panel\(s\)\ '.$panel.'\ of\ '.$panel_last;
	        $suximage_title[$N]    		= 'S14\ Hz\ wagc=\ '.$$ref_sugain_note[2].'\ f='.$$ref_sufilter_bandpass[1];
		$suximage_xlabel[$N]    	= $suximage_binhdr[$N];
		$suximage_tlabel[$N]  		= 'TWTT \(s\)';
		$suximage_box_width[$N] 	= 300;					
		$suximage_box_height[$N] 	= 700;					
		$suximage_X0[$N]        	= 0 + ($P-1) * 25;
		$suximage_Y0[$N]        	= 0 + ($P-1) * 25;
		$suximage_orientation[$N]	= 'normal';		
		$suximage_orientation[$N]	= 'normal';
		$suximage_orientation[$N]	= 'seismic';
		$suximage_hiclip[$N]            = 1; 
		$suximage_legend_on[$N]		= $on;
		$suximage_legend_off[$N]	= $off;
		$suximage_mute_picks_file[$N] 	= $DATA_SEISMIC_SU.'/'.$itemp_bot_mute_picks.$sufile_in[1];

$suximage[$P][$N] =  (" suximage				\\
		key=$suximage_binhdr[$N]			\\
		title=$suximage_title[$N]			\\
		label1=$suximage_tlabel[$N]			\\
		label2=$suximage_xlabel[$N]			\\
		legend=$suximage_legend_on[$N]			\\
		d2=$suximage_dx[$N]				\\
		f2=$suximage_x0[$N]				\\
		style=$suximage_orientation[$N]			\\
		xbox=$suximage_X0[$N]				\\
		ybox=$suximage_Y0[$N]				\\
		windowtitle=$suximage_windowtitle[$N]		\\
		wbox=$suximage_box_width[$N] 			\\
		hbox=$suximage_box_height[$N]			\\
		bclip=$suximage_hiclip[$N]                      \\
		perc=99						\\
		cmap=hsv1					\\
		va=1						\\
		xcur=3						\\
		mpicks=$suximage_mute_picks_file[$N]		\\
		");
$N=0;
}

#  DEFINE FLOW(S)
#  DEFINE FLOW(S)
	$flow[1] = (" 						\\
		$suwind[1] 	 				\\
		< $inbound[1] |					\\
		$sugain[2] |  					\\
		$sufilter[1] |					\\
		$suximage[1][1]					\\
		"); 

# RUN FLOW(S)
       system $flow[1]; 
       system 'echo', $flow[1];	
