#! /usr/bin/perl
# SCRIPT NAME
#itemp_Sumute_top.pl
# Purpose: Linear Mute of Data 
# Juan M. Lorenzo
# April 2 2009 
# Modified to work with erine lsu1 Nov 21, 2009
#
# Aug. 15, 2011- end of WWII in 1945 
# V 1.2
# toptom mute via one polygon file
# Modified to work with file checking options (files that =1 or =0) 
# on the first lines of special files.
# Use shell transparently to locate home directory before compilation
# V1.3
# for top muting

# LOAD SEISMIC UNIX GLOBAL SYSTEM LIBARAY
  use lib '/usr/local/pl/libAll';
  use SeismicUnix qw ($on $off $itemp_top_mute_picks_sorted_par_ $itemp_top_mute_num_points $suffix_mute $suffix_su);

# library path
  use lib './libAll';

# use library
   use Project;
  my $Project = new Project();
# import system variables
  my ($DATA_SEISMIC_SU) = $Project->DATA_SEISMIC_SU();

# library path
  use lib './libAll';
# use library
  use iTop_Mute qw ($file_name $binheader_type $panel_first $panel_last $panel_inc $traces_per_panel);

# sufile names
  $sufile_in[1] 		= $file_name;
  $sufile_out[1] 		= $sufile_in[1].$suffix_mute;
#  $sumute_inbound[1]	  	= $DATA_SEISMIC_SU.'/'.$sufile_in[1].$suffix_su;
  $suwind_inbound[1]	  	= $DATA_SEISMIC_SU.'/'.$sufile_in[1].$suffix_su;

# SUWIND  PARAMETERS
  my($ref_suwind_key,$ref_suwind_min,$ref_suwind_max,$suwind_Nmax) 		= iTop_Mute::suwind();


# SUWIND 
$suwind_N = $suwind_Nmax;
for($N=1;$N<=$suwind_N;$N++){
	$suwind[$N]  =  (" suwind 	            		\\
		key=$$ref_suwind_key[$N]			\\
		min=$$ref_suwind_min[$N]			\\
		max=$$ref_suwind_max[$N]			\\
              ");
}
$N=0;


# GAIN DATA
$N=1;
$sugain_pbal[$N] =1;
$sugain_note[$N] ='\ pbal='.$sugain_pbal[$N];
	$sugain[$N]  =  (" sugain 	            		\\
		pbal=	$sugain_pbal[$N]	  		\\
               ");
# GAIN DATA
$N=2;
$sugain_wagc[$N] = 0.1;
$sugain_note[$N] ='\ wagc='.$sugain_wagc[$N];
	$sugain[$N]  =  (" sugain 	            		\\
		wagc=$sugain_wagc[$N]			  	\\
		agc=1				  		\\
               ");

# FILTER  DATA
$sufilter_bandpass[1]= '0,3,300,600';
$sufilter_note[1] = '\ f='.$sufilter_bandpass[1];
	$sufilter[1] =  (" sufilter 	            		\\
		f=0,3,300,600					\\
               ");

# MUTE DATA 
  ($ref_sumute_key,$ref_sumute_pick_file_outbound,
   $ref_sumute_par_file_inbound,$ref_sumute_type,
   $sumute_Nmax) 				     = iTop_Mute::sumute();

	$sumute[1]  =  (" sumute 	            		\\
		par=$$ref_sumute_par_file_inbound[1]		\\
		key=$$ref_sumute_key[1]				\\
		mode=$$ref_sumute_type[1]			\\
              ");


# DISPLAY DATA
# display data
	for ($panel=$panel_first; $panel<=$panel_last; $panel = $panel + $panel_inc){	
$N=1;
$P=$panel;
		$suximage_binhdr[$N] 		= $binheader_type;
		$suximage_windowtitle[$N]	= '\('.$N.'\)\ '.'PICK\ TOP\ MUTE\ \ '.$file_name.'\ panel\(s\)\ '.$panel.'\ of\ '.$panel_last;
	        $suximage_title[$N]    		= 'S14\ Hz\ '.$sugain_note[2].$sufilter_note[1];
		$suximage_xlabel[$N]    	= $suximage_binhdr[$N];
		$suximage_tlabel[$N]  		= 'TWTT \(s\)';
		$suximage_box_width[$N] 	= 300;
		$suximage_box_height[$N] 	= 700;
		$suximage_X0[$N]        	= 300 + ($P-1) * 25;
		$suximage_Y0[$N]        	= 0 + ($P-1) * 25;
		$suximage_orientation[$N]	= 'normal';
		$suximage_orientation[$N]	= 'seismic';
		$suximage_hiclip[$N]            = 1; 
		$suximage_legend_on[$N]		= $on;
		$suximage_legend_off[$N]	= $off;
		$suximage_dx[$N]		= 1;
		$suximage_x0[$N]		= 1;

	$suximage[$P][$N] =  (" suximage			\\
		key=$suximage_binhdr[$N]			\\
		title=$suximage_title[$N]			\\
		label1=$suximage_tlabel[$N]			\\
		label2=$suximage_xlabel[$N]			\\
		legend=$suximage_legend_on[$N]			\\
		d2=$suximage_dx[$N]				\\
		f2=$suximage_x0[$N]				\\
		style=$suximage_orientation[$N]			\\
		xbox=$suximage_X0[$N]				\\
		ybox=$suximage_Y0[$N]				\\
		windowtitle=$suximage_windowtitle[$N]		\\
		wbox=$suximage_box_width[$N] 			\\
		hbox=$suximage_box_height[$N]			\\
		bclip=$suximage_hiclip[$N]                      \\
		perc=99						\\
		cmap=hsv1					\\
		va=1						\\
		xcur=3						\\
		");
$N=0;
}

# DISPLAY DATA
# display data
	for ($panel=$panel_first; $panel<=$panel_last; $panel = $panel + $panel_inc){	
$N=1;
$P=$panel;
		$suxwigb_windowtitle[$N]	= '\('.$N.'\)\ '.'S\ 14\ Hz\ '.$date.'\ panel\(s\)\ '.$panel.'\ of\ '.$panel_last;
		$suxwigb_title[$N]		= $$ref_suinterp_note[1].'\ '.$$ref_sugain_note[1]; 
		$suxwigb_box_width[$N] 		= 300;
		$suxwigb_box_height[$N] 	= 700;
		$suxwigb_tlabel[$N]    		= 'TWTT\ \(s\)';
		$suxwigb_xlabel[$N]    		= 'offset';
		$suxwigb_X0[$N]        		=  300 + ($P-1) * 25;
		$suxwigb_Y0[$N]			=  0 + ($P-1) * 25;
		$suxwigb_key[$N]		= 'offset';
		$suxwigb_hiclip[$N]             = 1;
		$suxwigb_mute_picks_file[$N] 	= $DATA_SEISMIC_SU.'/'.$itemp_top_mute_picks_.$sufile_in[1];
	$suxwigb[$P][$N] =  (" suxwigb				\\
		key=$suxwigb_key[$N]				\\
		title=$suxwigb_title[$N]			\\
		windowtitle=$suxwigb_windowtitle[$N]		\\
		hbox=$suxwigb_box_height[$N]			\\
		label1=$suxwigb_tlabel[$N]			\\
		label2=$suxwigb_xlabel[$N]			\\
		xbox=$suxwigb_X0[$N]				\\
		ybox=$suxwigb_Y0[$N]				\\
         	wbox=$suxwigb_box_width[$N]			\\
		va=1						\\
		xcur=2						\\
		clip=$suxwigb_hiclip[$N] 			\\
		");

$N=0;
}


# DISPLAY DATA

#  DEFINE FLOW(S)
	$flow[1] = (" 						\\
                $suwind[1]                                      \\
		< $suwind_inbound[1] |				\\
		$sumute[1] |	 				\\
		$sugain[2] | 					\\
		$sufilter[1] |					\\
		$suxwigb[1][1]					\\
		&						\\
		"); 


# RUN FLOW(S)
       system $flow[1]; 
       system 'echo', $flow[1];	
