#! /usr/bin/perl

=pod

=head1 DOCUMENTATION

=head2 SYNOPSIS 



# SCRIPT NAME
# itemp_Pick_SuDisp2_1.pl
# Purpose: Overplot picked tau-p picks 
# Juan M. Lorenzo
# Sept 22, 2011
# Modified to work with erine lsu1 Nov 21, 2009
#
# Aug. 15, 2011- end of WWII in 1945 
# V 1.2
# adapted from top mute via one polygon file
# Modified to work with file checking options (files that =1 or =0) 
# on the first lines of special files.
# Use shell transparently to locate home directory before compilation
# V1.3
# for top muting
# V 1. adapted from top muting V 1.3 on Sept. 22, 2011
# May 29, 2012
# V2_1 update to be compatible with iSuDisp2_1 which includes summing panels

=cut


        my $library_location;

        BEGIN {
                use Shell qw(echo);

                $home_directory = ` echo \$HOME`;
                chomp $home_directory;
       $library_location = $home_directory.'/lsu/libAll';
        }

# LOAD GENERAL PERL LIBRARY
  use lib $library_location;

# LOAD SEISMIC UNIX GLOBAL SYSTEM LIBARAY
  use lib '/usr/local/pl/libAll';
  use SeismicUnix qw ($on $off $itemp_surf_picks_sorted_par_  $itemp_surf_num_points_ $suffix_fp $suffix_su);
# $itemp_surf_picks_
# use library
  use Project;
  my $Project = new Project();

# import system variables
  my ($DATA_SEISMIC_SU) = $Project->DATA_SEISMIC_SU();

# library path
  use lib './libAll';

 # import system variables
  use iSurf2_1 qw ($file_name 
		 $d1 
		 $dt $interpolation 
		 $interpolation_factor 
		 $trace_separation 
		 $panel_first $panel_last 
		 $panel_inc  
		 $traces_per_panel 	 
		 $first_tracf_num  
		 $ns_fft
		);

#temporary
$plib ='/usr/local/pl/';

# INPUT SUFILE NAME 
$N=1;
 $sufile_in[$N] 	= $file_name;
$N=0;

# sufile names
$N=1;
  $inbound[$N]	  		= $DATA_SEISMIC_SU.'/'.$sufile_in[1].$suffix_su;
$N=0;

# OUTBOUND f-p FILE NAMES with path
 $N=1;
for ($panel = $panel_first; $panel <= $panel_last; $panel = $panel + $panel_inc) {
 $fp_outbound[$panel] = $DATA_SEISMIC_SU.'/'.$sufile_in[$N].$suffix_fp.'_panel_'.$panel.$suffix_su;
}
$N=0;

# OUTBOUND summed f-p FILE NAMES with path
 $N=1;
 $suop2_outbound_m[1] = $DATA_SEISMIC_SU.'/'.$sufile_in[$N].$suffix_fp.'_panels_All'.$suffix_su;
 $suop2_outbound_n[1] = $DATA_SEISMIC_SU.'/'.$sufile_in[$N].$suffix_fp.'_panels_temp'.$suffix_su;
$N=0;


# pick parameters
  ($ref_suximage_points_file,
	$suximage_num_points2plot) = iSurf2_1::ip_isurf_picks_file();

# SUGAIN parameters
  my($ref_sugain_wagc,$ref_sugain_agc,$ref_sugain_pbal,
	$ref_sugain_note,$sugain_Nmax)   = iSurf2_1::sugain();

# SUFILTER parameters 
  my($ref_sufilter_bandpass,$sufilter_Nmax) = iSurf2_1::sufilter();

 # SUTAUP parameters
  my($sutaup_pmin,
	$sutaup_pmax,
	$sutaup_dx,
	$sutaup_npoints,
	$sutaup_fmin,
	$sutaup_np,
	$sutaup_compute_in,
	$sutaup_Nmax
	)   = iSurf2_1::sutaup();


# SUINTERP parameters
 my($ref_suinterp_factor,$ref_suinterp_smooth_ns_t,
	$ref_suinterp_smooth_tr,$ref_suinterp_note,$suinterp_Nmax)	= iSurf2_1::suinterp();

# SMOOTH PARAMETERS
  my($ref_smooth2_ns,$ref_smooth2_num_trace,
	$ref_smooth2_r1,$smooth2_Nmax) 					= iSurf2_1::smooth2();

#SUWIND  PARAMETERS
  my($ref_suwind_key,$ref_suwind_min,$ref_suwind_max,
	$ref_suwind_note,
	$suwind_Nmax) 						= iSurf2_1::suwind();

#SUMAX parameters
  my($ref_sumax_mode,$ref_sumax_verbose_format,
	$ref_sumax_outpar,$sumax_Nmax) 				= iSurf2_1::sumax();

#SUSHW PARAMETERS
  my($ref_sushw_key,$ref_sushw_a,$ref_sushw_outbound,
	$sushw_Nmax) 						= iSurf2_1::sushw();

# GAWK PARAMETERS
  my($ref_gawk_num_lines,$ref_gawk_infile,$gawk_Nmax) 		= iSurf2_1::gawk();

# SUAMP parameters
  my($ref_suamp_outbound,$ref_suamp_freq_amp,$suamp_Nmax) 	= iSurf2_1::suamp();

# SUPTQUO PARAMETERS 
  my($ref_supanel_div_by_trace_PANEL,
	$ref_supanel_div_by_trace_TRACE,$suptquo_Nmax) 		= iSurf2_1::suptquo();

# SUADDHEAD parameters
  my($ref_suaddhead_ns,$suaddhead_Nmax) 			= iSurf2_1::suaddhead();

#A2B parameters
  my($ref_a2b_flts_per_line,$a2b_Nmax) 				= iSurf2_1::a2b();

# SUFLIP PARAMETERS
  my($ref_suflip_transpose,$suflip_Nmax) 			= iSurf2_1::suflip();


# FILTER 
  $sufilter_N = $sufilter_Nmax;
   for($N=1;$N<=$sufilter_N;$N++){
	$sufilter[$N] =  (" sufilter 		  		\\
		f=$$ref_sufilter_bandpass[$N]			\\
     ");
   }
$N=0;

# SUINTERP 
$suinterp_N = $suinterp_Nmax;
for($N=1;$N<=$suinterp_N;$N++){
        $num_tr_between[$N] = $$ref_suinterp_factor[$N] -1;	
								
	$suinterp[$N] =  (" suinterp 		  		\\
		ninterp=$num_tr_between[$N]			\\
		lent=$$ref_suinterp_smooth_ns_t[$N]		\\
		lenx=$$ref_suinterp_smooth_tr[$N]		\\
     ");
}
$N=0;

# SUGAIN 
$sugain_N=$sugain_Nmax;
for($N=1;$N<=$sugain_N;$N++) {;
	$sugain[$N]  =  (" sugain 	  			\\
		wagc=$$ref_sugain_wagc[$N]		  	\\
		pbal=$$ref_sugain_pbal[$N]	  		\\
		agc=$$ref_sugain_agc[$N]	  		\\
     ");
}
$N=0;


# SUTAUP
$sutaup_N = $sutaup_Nmax;
for($N=1;$N<=$sutaup_N;$N++) {;
	$sutaup[$N]  = (" sutaup				\\
		fmin=$sutaup_fmin				\\
		npoints=$sutaup_npoints				\\
		dx=$sutaup_dx				        \\
		option=$sutaup_compute_in 			\\
		np=$sutaup_np					\\
		pmin=$sutaup_pmin        			\\
	 	pmax=$sutaup_pmax        			\\
	");
}
$N=0;

# SUGAIN 
$sugain_N=$sugain_Nmax;
for($N=1;$N<=$sugain_N;$N++) {;
	$sugain[$N]  =  (" sugain 	  			\\
		wagc=$$ref_sugain_wagc[$N]		  	\\
		pbal=$$ref_sugain_pbal[$N]	  		\\
		agc=$$ref_sugain_agc[$N]	  		\\
     ");
}
$N=0;

# SMOOTH
$N=1;
$smooth2_N=$smooth2_Nmax;
for($N=1;$N<=$smooth2_N;$N++) {;
	$smooth2[$N] = (" smooth2				\\
		n1=$$ref_smooth2_ns[$N]				\\
		n2=$$ref_smooth2_num_trace[$N]			\\
		r1=$$ref_smooth2_r1[$N]				\\
		   ");
}
$N=0;


$N=1;
# SU FLIP DATA
$suflip_N=$suflip_Nmax;
for($N=1;$N<=$suflip_N;$N++) {;
        $suflip[$N] = (" suflip                                 \\
                        flip=$$ref_suflip_transpose[$N]              \\
                ");
}
$N=0;
# MULTIPLE-PANEL PROGRAMS

# SUWINDOW  
# by tracf
# by tracl
	for ($panel=$panel_first; $panel<=$panel_last; $panel = $panel + $panel_inc){
$P=$panel;
	$suwind[$P] =  (" suwind 	  			\\
		key=$$ref_suwind_key[$P]   				\\
		min=$$ref_suwind_min[$P]				\\
		max=$$ref_suwind_max[$P]   				\\
     ");

# GAWK
        $gawk[$P]=(" gawk \'NR<= $$ref_gawk_num_lines[$P] { print \$2 > \"/dev/stdout\" }\' $$ref_gawk_infile[$P] "); 

# SUMAX
        $sumax[$P]      =("sumax                                \\
                mode=$$ref_sumax_mode[$P]                            \\
                verbose=$$ref_sumax_verbose_format[$P]               \\
                outpar=$$ref_sumax_outpar[$P]                        \\
                ");

# SUPTQUO
        $supanel_div_by_trace[$P] = ( " suptquo                 \\
                ");
# SUSHW
        $sushw[$P]      = (" sushw                              \\
                key=$$ref_sushw_key[$P]                              \\
                a=$$ref_sushw_a[$P]                                  \\
                ");

# SELECT SPECTRAL MODE   
        $suamp[$P] =  (" suamp                                  \\
                        mode=$$ref_suamp_freq_amp[$P]                \\
     ");
}

## END MULTIPLE-PANEL PROGRAMS

# SUADDHEAD
$N=1;
	$suaddhead[$N]	= (" suaddhead				\\
		ns=$$ref_suaddhead_ns[$N]			\\
		");
$N=0;

# SUSHW
$N=1;
	$sushw[$N]	= (" sushw				\\
		key=$$ref_sushw_key[$N]				\\
		a=$$ref_sushw_a[$N]				\\
		");
$N=0;

#A2B
$N=1;
	$a2b[$N] 	= (" a2b				\\
			n1=$$ref_a2b_flts_per_line[$N]		\\
		");
$N=0;
# SPECTRAL ANALYSIS  
$N=1;
	$sufft[$N] =  (" sufft	 	  			\\
     ");
$N=0;

# SI
$$ref_dt[1] = $dt;
# increment between frequency values
$$ref_df[1] = $d1;

# DISPLAY DATA
## DISPLAY PARAMETERS 
# (flipped fast (1) direction is still vertical, under 'seismic' style)
$N=4;
   		$suximage_x0[$N]		= 1000 * $sutaup_pmin ;	
   		$suximage_dx[$N]		= 1000 * ($sutaup_pmax- $sutaup_pmin )/($sutaup_np-1);
   		$suximage_dy[$N]		= $d1 ;	
   		$suximage_y0[$N]		= 0 ;	
		$windowtitle_suximage[$N]	= '\('.$N.'\)\ '.'Sum\ of\ Amp\ spec\ '.$date.'\ panel\(s\)\ '.$panel_first.'\ to\ '.$panel_last.'\ every\ '.$panel_inc.'\ RECENT\ PICKS';
	        $title_suximage[$N]    		= 'file\ '.$sufile_in[1].'\ '.$$ref_suinterp_note[1].'\ '.$$ref_suwind_note[$P];
		$ylabel_suximage[$N]  		= 'frequency\ \(Hz\)';
		$xlabel_suximage[$N]    	= 'p\ s\/km';
		$box_width_suximage[$N] 	= 700;
		$box_height_suximage[$N] 	= 300;
		$X0_suximage[$N]        	= 0 + ($P-1) * 25;
		$Y0_suximage[$N]        	= 700 + ($P-1) * 25;
		$orientation_suximage[$N]	= 'seismic';
		$orientation_suximage[$N]	= 'normal';
		$suximage_lowclip[$N]		= 0;
		$suximage_hiclip[$N]		= 10;

		#$suximage_pick_file[$N]		= $DATA_SEISMIC_SU.'/'.$itemp_surf_picks_.$sufile_in[1];
		$suximage_pick_file[$N]		= $$ref_suximage_points_file[1];
  	print("You just picked $suximage_num_points2plot points\n");

	$suximage[$P][$N] =  (" suximage			\\
		title=$title_suximage[$N]			\\
		label1=$ylabel_suximage[$N]			\\
		label2=$xlabel_suximage[$N]			\\
		cmap=hsv8					\\
		legend=1					\\
		f1=$suximage_y0[$N]				\\
		d1=$suximage_dy[$N]				\\
		f2=$suximage_x0[$N]				\\
		d2=$suximage_dx[$N]				\\
		style=$orientation_suximage[$N]			\\
		xbox=$X0_suximage[$N]				\\
		ybox=$Y0_suximage[$N]				\\
		windowtitle=$windowtitle_suximage[$N]		\\
		wbox=$box_width_suximage[$N] 			\\
		hbox=$box_height_suximage[$N]			\\
		bclip=$suximage_hiclip[$N]			\\
		wclip=$suximage_lowclip[$N]			\\
		npair=$suximage_num_points2plot			\\
		curvecolor=black				\\
		curve=$suximage_pick_file[$N]			\\
		");
	#	curve=$$ref_suximage_points_file[1]		\\
$N=0;
		#mpicks=$suximage_pick_file[$N]			\\

for ($panel=$panel_first,$num_panels=1; $panel<=$panel_last ;$panel = $panel + $panel_inc,$num_panels++){	
$P=$panel;
  if ($interpolation == $on) {
# DEFINE FLOW(S)
# output panel
	$flow[$P][4] = (" 					\\
    		$suwind[$P]					\\
		< $inbound[1]	|				\\
		$suinterp[1] 	|				\\
		$sufilter[1]	|				\\
		$sugain[1]	|				\\
		$sutaup[1]	|				\\
		$sufft[1] 	|				\\
		$suamp[$P] 	>				\\
		$$ref_suamp_outbound[$P]			\\
								\\
		");
	
	
# DEFINE FLOW(S)
# output smoothed trace 
	$flow[$P][5] = (" 					\\
    		$suwind[$P]					\\
		< $inbound[1]	|				\\
		$suinterp[1] 	|				\\
		$sufilter[1]	|				\\
		$sugain[1]	|				\\
		$sutaup[1]	|				\\
		$sufft[1] 	|				\\
		$suamp[$P] 	|				\\
		$suflip[1]  	|				\\
		$sumax[$P] ;					\\
		$gawk[$P]   	|     				\\
		$a2b[1]		|				\\
		$smooth2[1]     |				\\
		$suaddhead[1]	|				\\
		$sushw[$P] 	> 				\\
		$$ref_sushw_outbound[$P]			\\
								\\
		");
		
#  DEFINE FLOW(S)
# plot
# normalize f-p panel
#	$flow[$P][6] = (" 					\\
#		$supanel_div_by_trace[$P]			\\
#		$$ref_supanel_div_by_trace_PANEL[$P]		\\
#		$$ref_supanel_div_by_trace_TRACE[$P]  |		\\
#		$suximage[$P][4]				\\
#		&						\\
#		");

#  DEFINE FLOW(S)
# create normalized f-p panel
#
	$flow[$P][7] = (" 					\\
		$supanel_div_by_trace[$P]			\\
		$$ref_supanel_div_by_trace_PANEL[$P]		\\
		$$ref_supanel_div_by_trace_TRACE[$P]  		\\
		> $fp_outbound[$P]				\\
								\\
		");  	

# sum normalized f-p panels
#   on the first panel
   	if ($num_panels == 1)	{       	
                #print("first panel is: $suop2_outbound_m[1]\n");
		$flow[$P][8] = (" cp $fp_outbound[$P]		\\
				     $suop2_outbound_m[1]	\\
								\\
	        ");
   	}

   	if ($num_panels > 1) { 
                #print("num panels $num_panels\n");
		$flow[$P][8] = (" 					\\
			suop2						\\
			$suop2_outbound_m[1]				\\
			$fp_outbound[$P]				\\
			op=sum						\\
			> $suop2_outbound_n[1] ;			\\
			cp $suop2_outbound_n[1]	$suop2_outbound_m[1]	\\
									\\
			"); 
   	}

 #end if
 }
   elsif ($interpolation == $off) {
 
# DEFINE FLOW(S)
# output panel
	$flow[$P][4] = (" 					\\
    		$suwind[$P]					\\
		< $inbound[1]	|				\\
		$sufilter[1]	|				\\
		$sugain[1]	|				\\
		$sutaup[1]	|				\\
		$sufft[1] 	|				\\
		$suamp[$P] 	>				\\
		$$ref_suamp_outbound[$P]			\\
								\\
		");
	
	
# DEFINE FLOW(S)
# output smoothed trace 
	$flow[$P][5] = (" 					\\
    		$suwind[$P]					\\
		< $inbound[1]	|				\\
		$sufilter[1]	|				\\
		$sugain[1]	|				\\
		$sutaup[1]	|				\\
		$sufft[1] 	|				\\
		$suamp[$P] 	|				\\
		$suflip[1]  	|				\\
		$sumax[$P] ;					\\
		$gawk[$P]   	|     				\\
		$a2b[1]		|				\\
		$smooth2[1]     |				\\
		$suaddhead[1]	|				\\
		$sushw[$P] 	> 				\\
		$$ref_sushw_outbound[$P]			\\
								\\
		");
		
#  DEFINE FLOW(S)
# plot
# normalize f-p panel
#	$flow[$P][6] = (" 					\\
#		$supanel_div_by_trace[$P]			\\
#		$$ref_supanel_div_by_trace_PANEL[$P]		\\
#		$$ref_supanel_div_by_trace_TRACE[$P]  |		\\
#		$suximage[$P][4]				\\
#		&						\\
#		"); 

#  DEFINE FLOW(S)
# output normalized f-p panel
	$flow[$P][7] = (" 					\\
		$supanel_div_by_trace[$P]			\\
		$$ref_supanel_div_by_trace_PANEL[$P]		\\
		$$ref_supanel_div_by_trace_TRACE[$P] > 		\\
		$fp_outbound[$P]				\\
								\\
		"); 

# sum normalized f-p panels
#   on the first panel
   	if ($num_panels == 1)	{       	
                #print("first panel is: $suop2_outbound_m[1]\n");
		$flow[$P][8] = (" cp $fp_outbound[$P]		\\
				     $suop2_outbound_m[1]	\\
								\\
	        ");
   	}


 

#end of elseif
   }
# end for loop
}
# DEFINE FLOW
# outside loop
# plot final sum of normalized        	
# f-p panels
	$flow[$P][9] = (" 					\\
		$suximage[$P][4]			\\
		< $suop2_outbound_m[1] 				\\
		&						\\
		");

# RUN FLOW(S)
for ($panel=$panel_first; $panel<=$panel_last ;$panel = $panel + $panel_inc){	
$P=$panel;
#       system $flow[$P][4]; 
#       system 'echo', $flow[$P][4];	

#       system $flow[$P][5]; 
#       system 'echo', $flow[$P][5];	

# normalize panel and output to monitor
#print("Working on panel $P\n");
#       system $flow[$P][6]; 
#       system 'echo', $flow[$P][6];

# outputs f-p data sets 
# normalize panel and output to file
# 	system $flow[$P][7]; 
	#system 'echo', $flow[$P][7];	

# sums f-p data sets 
# 	system $flow[$P][8]; 
 	#system 'echo', $flow[$P][8];	

	
}
# RUN FLOW(S)
# plots final sum f-p data sets 	

 	system $flow[$P][9]; 
 	#system 'echo', $flow[$P][9];	

